### ISSUE TITLE
rospy.exceptions.ROSInitException: time is not initialized. Have you called init_node()?

### ISSUE THREAD

**Issue by Pro** [ros-controls/ros_control#349]
I have a newly installed ubuntu 18.04.1.

I installed `ros-melodic-desktop-full` and `ros-melodic-controller-manager`.

When I try to execute the controller manager with `rosrun controller_manager controller_manager spawn arm_controller` it fails:

```
$ rosrun controller_manager controller_manager spawn arm_controller
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/controller_manager/controller_manager", line 58, in <module>
    controller_manager_interface.load_controller(c)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/controller_manager/controller_manager_interface.py", line 56, in load_controller
    rospy.wait_for_service('controller_manager/load_controller')
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 160, in wait_for_service
    rospy.core.logwarn_throttle(10, "wait_for_service(%s): failed to contact, will keep trying"%resolved_name)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/core.py", line 243, in logwarn_throttle
    _base_logger(msg, logger_throttle=period, logger_level='warn')
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/core.py", line 184, in _base_logger
    if _logging_throttle(caller_id, throttle):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/core.py", line 222, in __call__
    now = rospy.Time.now()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/rostime.py", line 155, in now
    return get_rostime()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/rostime.py", line 190, in get_rostime
    raise rospy.exceptions.ROSInitException("time is not initialized. Have you called init_node()?")
rospy.exceptions.ROSInitException: time is not initialized. Have you called init_node()?
```
The installed version is: 0.15.0-0bionic.20180606.203244

Do you have an idea how I can fix this? It looks like the python script is missing somewhere a `rospy.init_node()`?

**Comment by Pro** [comment]
I was able to temprarily fix this by changing:
https://github.com/ros-controls/ros_control/blob/0a7751fd87337bcee14f6b282a9ed40c3bf46867/controller_manager/scripts/controller_manager#L31

from
```python

if __name__ == '__main__':
    args = rospy.myargv()
    if len(args) < 2:
        print_usage()
```

to
```python

if __name__ == '__main__':
    args = rospy.myargv()
    rospy.init_node('controller_manager', anonymous=True)
    if len(args) < 2:
        print_usage()
```

**Comment by bmagyar** [comment]
Hi, thanks for the heads up!

Could you please submit a pull request with these changes?
