### ISSUE TITLE
gethandle() error

### ISSUE THREAD

**Issue by EricWang1hitsz** [ros-controls/ros_control#467]
hello, I created a new hardware interface and controller, when I run 'gethandle()', it errors.

```
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/controller_manager/spawner", line 207, in <module>
    if __name__ == '__main__': main()
  File "/opt/ros/kinetic/lib/controller_manager/spawner", line 185, in main
    resp = load_controller(name)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 525, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
rospy.service.ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details
[WARN] [1593422088.174780]: Controller Spawner error while taking down controllers: unable to connect to service: [Errno 111] Connection refused

```

**Comment by bmagyar** [comment]
This is just the spawner. Your new hw interface and controller probably crashed both the controller_manager and all around it.
